# Generated by Django 3.1 on 2020-08-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_auto_20200825_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ratting_hotel',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Hotel.hotel'),
            preserve_default=False,
        ),
    ]
