# Generated by Django 3.1 on 2020-08-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_auto_20200825_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='expire',
            field=models.DateTimeField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
