# Generated by Django 3.1 on 2020-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_combo_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='expire',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
