# Generated by Django 3.1 on 2020-08-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_auto_20200825_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='expire',
        ),
    ]
