# Generated by Django 3.1 on 2020-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='expire',
            field=models.DateTimeField(blank=True),
        ),
    ]
